#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	START_BUTTON,
	BET_BUTTON,
	SPIN_BUTTON,
	QUIT_BUTTON,
	RESET_BUTTON,
	SLOT_MACHINE,
	SLOT_LEFT,
	SLOT_MIDDLE,
	SLOT_RIGHT,
	NUM_OF_TYPES
};

#endif /* defined (__GAME_OBJECT_TYPE__)*/